config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'registrations'}

  devise_scope :user do
	  authenticated :user do
	    root 'posts#feed', as: :user_feed
	  end

	  unauthenticated do
	    root 'pages#home', as: :root
	  end
	end

	resources :posts, only: [:create, :destroy] do
		collection do
			get :feed
			get :public_feed
		end
	end

	resources :users, only: [:index] do
		member do
			post :follow
			post :unfollow
			get :notifications
		end
		collection do
			post :search
		end
	end

	resources :users, only: [:show], path: '/'
end

app/models/notification.rb
class Notification < ActiveRecord::Base
	belongs_to :sender, foreign_key: :sender_id, class_name: "User"
	belongs_to :receiver, foreign_key: :receiver_id, class_name: "User"

	validates :sender, :receiver, presence: true
	
	scope :unread, -> {
		where(read: false)
	} 

	def self.send_notification(sender, receiver)
		self.create(
			sender: sender,
			receiver: receiver
		)
	end
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :text, length: { maximum: 140 }
	validates :user_id, presence: true
	belongs_to :user

	def username
		"@#{user.username}"
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  has_many :posts, dependent: :destroy
  has_many :publishers, foreign_key: :publisher_id, class_name: "User"
  has_many :publishers_posts, through: :publishers, source: :posts
  has_many :notifications, foreign_key: :receiver_id, dependent: :destroy
  
  validates :username, :fullname, presence: true
  validates :username, uniqueness: true

  def add_publisher(user)
  	self.publishers << user
    Notification.send_notification(self, user)
  end

  def feed_posts
  	(self.posts + self.publishers_posts).sort_by(&:created_at).reverse
  end

  def to_param
    self.username
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(user)
  	feed_posts_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@recent_posts = Post.last(3).reverse
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, except: :public_feed

  def feed
    @posts = current_user.feed_posts
  end

  def public_feed
    @posts = Post.last(30).reverse
  end

  def create
  	@post = current_user.posts.create(params[:post].permit(:text))
		@posts = current_user.feed_posts
		respond_to do |format|
      format.html { redirect_to feed_posts_path }
			format.js
		end
  end

  def destroy
  	@post = Post.find(params[:id])
  	@post.destroy if @post.user == current_user
  	@posts = current_user.feed_posts
  	respond_to do |format|
      format.html { redirect_to feed_posts_path }
	  	format.js
  	end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

    def sign_up_params
      allow = [:email, :password, :password_confirmation, :username, :fullname]
      params.require(resource_name).permit(allow)
    end

    def account_update_params
	    allow = [:email, :password, :password_confirmation, 
	    	:current_password, :username, :fullname, :avatar]
      params.require(resource_name).permit(allow)
	  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, only: [:unfollow, :notifications]

  def show
  	@user = User.find_by(username: params[:id])
    @posts = @user.posts
  end

  def index
    @users = User.all
  end

  def follow
    if user_signed_in?
      @user = User.find_by(username: params[:id])
      current_user.add_publisher(@user)
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end
    else
      redirect_to new_user_registration_path
    end
  end

  def unfollow
    @user = User.find_by(username: params[:id])
    current_user.publishers.delete(@user)
    respond_to do |format|
      format.html { redirect_to :back }
      format.js { render :follow }
    end
  end

  def notifications
    @user = current_user
    @notifications = @user.notifications
    @notifications.each do |notification|
      notification.update_attribute :read, true
    end
  end

  def search
    @users = User.where("username LIKE ?", "%#{params[:search][:text]}%")
    respond_to do |format|
      format.html { render :index }
      format.js
    end    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def parse_text(text)
		parsed_text = text.gsub(/\@(\w)*/) do 
			mention = $&
			link = mention.gsub("@","")
			link_to "#{mention}", "/#{link}"
		end
		h auto_link(parsed_text)
	end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation">
      <p>#{messages}</p>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    resource.errors.empty? ? false : true
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Microtweet" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
  </head>
  <body id="home">
    <%= render "shared/header" %>

    <div class="container">
      <div id="main-content" class="row">
        <div class="col-md-8 col-md-offset-2">
          <%= bootstrap_flash %>
        </div>
        <div class="col-lg-12">
          <%= yield %>
        </div>
      </div><!--/row-->
    </div> <!-- /container -->

    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/_new_registration.html.erb
<%= form_for(:user, url: registration_path(:user)) do |f| %>
  <div class="form-group">
    <%= f.email_field :email, class: 'form-control', placeholder: "E-mail" %>
  </div>

  <div class="form-group">
    <%= f.password_field :password, class: 'form-control', placeholder: "Password" %>
  </div>

  <div class="form-group">
    <%= f.text_field :fullname, class: 'form-control', placeholder: "Full Name" %>
  </div>

  <div class="form-group">
    <%= f.text_field :username, class: 'form-control', placeholder: "Username" %>
  </div>

  <div class="actions text-right">
    <%= f.submit "Sign up", class: "btn", id: "main-signup" %>
  </div>
<% end %>

app/views/pages/_new_session.html.erb
<%= form_for(:user, url: session_path(:user)) do |f| %>
  <div class="form-group">
    <%= f.email_field :email, class: 'form-control', placeholder: "E-mail", id: "login_user_email" %>
  </div>

  <div class="form-group">
    <%= f.password_field :password, class: 'form-control', placeholder: "Password", id: "login_user_password" %>
  </div>

  <div class="row">
    <small>
    <div class="col-md-6">
      <%= f.check_box :remember_me %>
      <%= f.label :remember_me %>
    </div>
    <div class="col-md-6 text-right">
      <%= link_to "Forgot your password?", new_password_path(:user) %>
    </div>
    </small>
  </div>

  <div class="actions text-right">
    <%= f.submit "Log in", class: "btn", id: "main-login" %>
  </div>
<% end %>

app/views/pages/home.html.erb
<div id="home-content" class="row">
  <div class="col-md-6 col-md-offset-1">
    <h1>Microtweet</h1>
    <h2>A new way to see what your friends are doing.</h2>

    <div class="well">
      <h3>Recent Activity</h3>
      <%= render "posts/posts", posts: @recent_posts %>
      <div class="text-right">
        <%= link_to "See more →", public_feed_posts_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="well">
      <%= render "new_session" %>
    </div>
    <div class="well">
      <h3>Sign up</h3>
      <%= render "new_registration" %>
    </div>
  </div>
</div>

app/views/posts/_no_activity_message.html.erb
<h4 class="text-center text-muted">There's no Activity yet, <%= link_to "Find Users", users_path %>.</h4>

app/views/posts/_posts.html.erb
<% posts.each_with_index do |post, i| %>
	<div class="row">
		<div class="col-xs-2">
			<%= image_tag post.user.avatar.url(:thumb), class: "post-avatar thumbnail" %>
		</div>
		<div class="col-xs-9">
			<strong><%= post.user.fullname %></strong> ·
			<span class="text-muted">
				<%= link_to post.username, user_path(post.user) %> ·
				<%= time_ago_in_words(post.created_at) %>
			</span>
			<p><%= parse_text(post.text) %></p>
		</div>
		<div class="col-xs-1">
			<% if post.user == current_user %>
			<div class="text-right">
				<%= link_to "x", post_path(post), class: "btn btn-default btn-xs", method: :delete, remote: true %>
			</div>
			<% end -%>
		</div>
	</div>
	<% unless i == posts.length-1 %>
		<hr>
	<% end -%>
<% end -%>

app/views/posts/create.js.erb
$("#posts").html("<%= escape_javascript(render :partial => 'posts/posts', :locals => { :posts => @posts }) %>"); 
$("#posts").effect("highlight", {}, 3000);
$("#post-counter").text("0");
$("#post_text").val('');

app/views/posts/destroy.js.erb
<% if @posts.present? %>
	$("#posts").html("<%= escape_javascript(render :partial => 'posts/posts', :locals => { :posts => @posts }) %>"); 
<% else %>
	$("#posts").html("<%= escape_javascript(render :partial => 'posts/no_activity_message') %>"); 
<% end %>

app/views/posts/feed.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
  	<div class="well">
	  	<% if user_signed_in? %>
	  		<%= form_for Post.new, remote: true do |f| %>
	  			<div class="form-group">
				    <%= f.text_area :text, class: 'form-control', placeholder: "Say something interesting" %>
				  </div>
				  <div class="row">
				  	<div class="col-md-1 col-md-offset-9">
					  	<div id="post-counter" class="text-muted text-right">
					  		0
					  	</div>
				  	</div>
				  	<div class="col-md-2 text-right">
					  	<%= f.submit "Post".html_safe, class: "btn btn-primary", id: "post-btn" %>
				  	</div>
				  </div>
	  		<% end -%>
	  	<% end -%>
	  </div>
    <h2>Activity Feed</h2>
    <div id="posts" class="well">
    	<% if @posts.present? %>
	      <%= render "posts", posts: @posts %>
	    <% else %>
	    	<%= render "no_activity_message" %>
	    <% end -%>
    </div>
  </div>
</div>

<script type="text/javascript">
	$(document).ready(function() {
		$('#post_text').keyup(function () {
		  var max = 140;
		  var len = $(this).val().length;
		  $("#post-counter").text(len);
		  if (len > max) {
		    $("#post-btn").prop("disabled", true);
		  } else {
		    $("#post-btn").prop("disabled", false);
		  }
		});
	});
</script>

app/views/posts/public_feed.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h2>Recent Activity</h2>
    <div id="posts" class="well">
    	<% if @posts.present? %>
	      <%= render "posts", posts: @posts %>
	    <% else %>
	    	<h4 class="text-center text-muted">There's no Activity yet, <%= link_to "Find Users", users_path %>.</h4>
	    <% end -%>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="footer">
	<div class="container">
		<div class="row">
			<div class="col-md-2">
				&reg Microtweet
			</div>
		</div>
	</div>
</footer>

app/views/shared/_header.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to root_path, class: "navbar-brand" do %>
      <i class="fa fa-slack"></i> Microtweet
    <% end -%>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <%= link_to notifications_user_path(current_user) do %>
              <i class="fa fa-bell"></i>
              <% unless current_user.notifications.unread.count.zero? %>
                <span class="badge badge-warning"><%= current_user.notifications.unread.count %></span>
              <% end -%>
            <% end -%>
          </li>

          <li><%= link_to "Feed", feed_posts_path %></li>
          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to "Profile", edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Signup", new_user_registration_path %></li>
        <% end -%>
      </ul>
    </div>
  </div>
</div>

app/views/users/_follow_btn.html.erb
<div id="follow-btn-<%= user.id %>">
	<% if user_signed_in? %>
		<% unless current_user == user %>	
			<% if current_user.publishers.include?(user) %>
				<%= button_to "Unfollow", unfollow_user_path(user) , class: "btn btn-warning btn-unfollow", remote: true %>
			<% else %>
			  <%= button_to "Follow", follow_user_path(user), class: "btn btn-primary btn-follow", remote: true %>
			<% end -%>
		<% end -%>
	<% else %>
		<%= button_to "Follow", follow_user_path(user), class: "btn btn-primary btn-follow" %>
	<% end -%>
</div>

app/views/users/_users.html.erb
<% if users.present? %>
	<% users.each_with_index do |user, i| %>
		<div class="row">
			<div class="col-xs-2">
				<%= image_tag user.avatar.url(:thumb), class: "post-avatar thumbnail" %>
			</div>
			<div class="col-xs-9">
				<strong><%= link_to user.fullname, user_path(user) %></strong> ·
				<span class="text-muted">
					<%= user.username %> ·
					<%= pluralize(user.posts.count, "post") %>
				</span>
				<% unless user == current_user %>
					<p><%= render 'follow_btn', user: user %></p>
				<% end -%>
			</div>
		</div>
		<% unless i == @users.length-1 %>
			<hr>
		<% end -%>
	<% end -%>
<% else %>
	<h4 class="text-center text-muted">There's no User.</h4>
<% end -%>

app/views/users/follow.js.erb
$("#follow-btn-<%= @user.id %>").html("<%= escape_javascript(render :partial => 'users/follow_btn', :locals => { :user => @user }) %>"); 

app/views/users/index.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="row">
      <div class="col-md-7">
      	<h2>Users</h2>
      </div>
      <div class="col-md-5">
        <%= form_for :search, url: search_users_path, remote: true do |f| %>
          <div id="search-users" class="input-group">
            <div class="form-group text-right">
              <%= f.text_field :text, id: "search-user-field", class: 'form-control', placeholder: "Search by username" %>
            </div>
            <span class="input-group-btn">
              <%= f.submit "Search", class: "btn btn-default", id: "btn-search" %>
            </span>
          </div><!-- /input-group -->
        <% end -%>
      </div>
    </div>
  	<div id="users" class="well">
			<%= render "users", users: @users %>
  	</div>
  </div>
</div>

app/views/users/notifications.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
  	<h2>Notifications</h2>
  	<div class="well">
  		<% @notifications.each_with_index do |notification, i| %>
        <p><strong><%= link_to notification.sender.fullname, user_path(notification.sender) %></strong> started to follow you.</p>
				<% unless i == @notifications.length-1 %>
					<hr>
				<% end -%>
  		<% end -%>
  	</div>
  </div>
</div>

app/views/users/search.js.erb
$("#users").html("<%= escape_javascript(render :partial => 'users/users', :locals => { :users => @users }) %>"); 

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
  	<div class="row">
	  	<div class="col-md-10">
		    <h2><%= @user.fullname.possessive %> Feed</h2>
	  	</div>
	  	<div class="col-md-2 text-right">
	  		<%= render 'follow_btn', user: @user %>
	  	</div>
  	</div>
    <div id="posts" class="well">
      <%= render "posts/posts", posts: @posts %>
    </div>
  </div>
</div>